export const episode1 = {
  "a": "to",
  "abraço": "hug",
  "acaba": "finishes",
  "acabado": "finished",
  "acabar": "to finish",
  "acham": "they think",
  "achas": "you think",
  "acidente": "accident",
  "acontece": "happens",
  "acontecer": "to happen",
  "aconteceu": "happened",
  "acontecia": "was happening",
  "adiantava": "it helped",
  "adoro": "I love",
  "adoçante": "sweetener",
  "advogado": "lawyer",
  "afogado": "drowned",
  "agora": "now",
  "agradece": "thank you",
  "aguenta": "endure",
  "ai": "oh",
  "ainda": "still",
  "ajuda": "help",
  "ajudar": "to help",
  "alarme": "alarm",
  "aldeias": "villages",
  "algum": "some",
  "alguma": "some",
  "algumas": "some",
  "alguém": "someone",
  "alimentares": "food",
  "almoço": "lunch",
  "aluno": "student",
  "alô": "hello",
  "amanhã": "tomorrow",
  "amarga": "bitter",
  "amarrada": "tied",
  "amendoins": "peanuts",
  "amigo": "friend",
  "amores": "loves",
  "américa": "america",
  "anda": "he/she walks",
  "andamos": "we walk",
  "andar": "to walk",
  "andas": "you walk",
  "animais": "animals",
  "anjo": "angel",
  "anos": "years",
  "antes": "before",
  "ao": "to the",
  "aonde": "where",
  "aos": "to the",
  "apanhados": "caught",
  "apanhe": "catch",
  "apanhámos": "we caught",
  "apareceram": "appeared",
  "aparecia": "appeared",
  "apertadas": "tight",
  "apreensão": "apprehension",
  "apresentar": "to present",
  "aproveitar": "to enjoy",
  "aquela": "that one",
  "aquelas": "those",
  "aquele": "that",
  "aqui": "here",
  "ardente": "burning",
  "areia": "sand",
  "arquipélago": "archipelago",
  "arranjar": "to arrange",
  "arrestados": "arrested",
  "arruda": "rue",
  "artística": "artistic",
  "as": "the",
  "assim": "so",
  "assinar": "to sign",
  "atento": "attentive",
  "atirar": "to throw",
  "atlântico": "atlantic",
  "atracar": "to dock",
  "atrasado": "late",
  "atravessámos": "we crossed",
  "atrás": "behind",
  "até": "until",
  "autocarro": "bus",
  "autorrádios": "car radios",
  "autógrafo": "autograph",
  "avançado": "advanced",
  "avisei": "I warned",
  "açores": "azores",
  "açoriano": "azorean",
  "açorianos": "azoreans",
  "aí": "there",
  "baboso": "drooling",
  "balcão": "counter",
  "banha": "lard",
  "banho": "bath",
  "barco": "boat",
  "bastava": "it was enough",
  "bebe": "he/she drinks",
  "bela": "beautiful",
  "beleza": "beauty",
  "bem": "well",
  "benefício": "benefit",
  "benfica": "benfica",
  "betas": "betas",
  "bicha": "queue",
  "bico": "beak",
  "blica": "blica",
  "blicas": "blicas",
  "boa": "good",
  "bobina": "coil",
  "boca": "mouth",
  "bocadinho": "little bit",
  "bocado": "bit",
  "bom": "good",
  "bonita": "pretty",
  "bonitos": "pretty",
  "borrado": "erased",
  "boston": "boston",
  "brasil": "brazil",
  "bretanha": "britain",
  "bruna": "bruna",
  "buscar": "to look for",
  "c'um": "with a",
  "cabelo": "hair",
  "cabeça": "head",
  "cadela": "bitch",
  "cadelinha": "little bitch",
  "café": "coffee",
  "cagar": "to shit",
  "cai": "falls",
  "cair": "to fall",
  "caiu": "fell",
  "cala": "shut up",
  "calma": "calm",
  "camioneta": "van",
  "cana": "cane",
  "cancro": "cancer",
  "candidata": "candidate",
  "caneta": "pen",
  "capotou": "crashed",
  "cara": "face",
  "caralho": "cock",
  "caralhos": "cocks",
  "carga": "load",
  "carinha": "cute face",
  "carlinhos": "carlinhos",
  "carregado": "loaded",
  "carro": "car",
  "carta": "letter",
  "casa": "house",
  "castiga": "punishes",
  "categoria": "category",
  "caudas": "tails",
  "causa": "cause",
  "cedo": "early",
  "centenas": "hundreds",
  "cento": "hundred",
  "certo": "right",
  "chama": "flame",
  "chamam": "they call",
  "chamar": "to call",
  "charro": "joint",
  "chega": "arrives",
  "chegar": "to arrive",
  "chegaste": "you arrived",
  "chegou": "arrived",
  "cheio": "full",
  "cheira": "smells",
  "cheirar": "to smell",
  "chicharros": "chicharros",
  "chico": "chico",
  "chove": "it's raining",
  "cidade": "city",
  "cidadãos": "citizens",
  "cima": "top",
  "cinema": "cinema",
  "cinquenta": "fifty",
  "ciúmes": "jealousy",
  "cliente": "client",
  "cobrir": "to cover",
  "coca": "coke",
  "cocaína": "cocaine",
  "coincidência": "coincidence",
  "coisa": "thing",
  "coisas": "things",
  "coisinha": "little thing",
  "colombiano": "colombian",
  "com": "with",
  "comer": "to eat",
  "começou": "started",
  "comiam": "they ate",
  "como": "how",
  "comprar": "to buy",
  "compras": "shopping",
  "comprava": "bought",
  "confundamos": "we confuse",
  "confusão": "confusion",
  "conheces": "you know",
  "connosco": "with us",
  "consegues": "you can",
  "conselheira": "counselor",
  "contabilizou": "accounted",
  "contagem": "count",
  "contar": "to count",
  "contigo": "with you",
  "continuaremos": "we will continue",
  "contos": "tales",
  "contra": "against",
  "copo": "glass",
  "corpo": "body",
  "corre": "runs",
  "corrente": "current",
  "correntes": "currents",
  "correr": "to run",
  "correu": "ran",
  "cortar": "to cut",
  "coser": "to sew",
  "costa": "coast",
  "costumam": "they usually",
  "coxeias": "lanes",
  "craque": "star",
  "cricas": "cricas",
  "cristo": "christ",
  "cruzada": "crusade",
  "cruzaram": "crossed",
  "cu": "ass",
  "cuidado": "careful",
  "culpa": "blame",
  "custa": "costs",
  "cá": "here",
  "cão": "dog",
  "da": "of the",
  "daqui": "from here",
  "dar": "to give",
  "dares": "you give",
  "das": "of the",
  "dava": "gave",
  "de": "of",
  "declarações": "statements",
  "decorre": "it happens",
  "decrescente": "decreasing",
  "defende": "defends",
  "dei": "I gave",
  "deixa": "leave",
  "deixamos": "we leave",
  "deixar": "to leave",
  "depois": "after",
  "der": "give",
  "desanda": "go away",
  "descansar": "to rest",
  "descontrai": "relax",
  "desculpa": "sorry",
  "desde": "since",
  "desejo": "desire",
  "despejarem": "to evict",
  "desses": "of those",
  "destes": "of these",
  "deu": "gave",
  "deus": "god",
  "deve": "must",
  "deviam": "they should",
  "devias": "you should",
  "devíamos": "we should",
  "dez": "ten",
  "dezenas": "dozens",
  "dia": "day",
  "diga": "say",
  "digo": "I say",
  "dinheiro": "money",
  "direito": "right",
  "diretor": "director",
  "disparar": "to shoot",
  "disse": "said",
  "disser": "say",
  "disseste": "you said",
  "distraídos": "distracted",
  "dividimos": "we divide",
  "dividiram": "they divided",
  "divisória": "dividing",
  "diz": "says",
  "dizem": "they say",
  "dizemos": "we say",
  "dizer": "to say",
  "do": "of the",
  "dois": "two",
  "dom": "dom",
  "dono": "owner",
  "dos": "of the",
  "doutor": "doctor",
  "dr": "dr",
  "droga": "drug",
  "duas": "two",
  "dura": "lasts",
  "dá": "gives",
  "dê": "give",
  "e": "and",
  "eduardo": "eduardo",
  "eh": "eh",
  "ei": "hey",
  "ela": "she",
  "ele": "he",
  "em": "in",
  "embaixada": "embassy",
  "embora": "although",
  "empurra": "push",
  "encolhe": "shrink",
  "encomendou": "ordered",
  "encontramo": "we find",
  "enganas": "you deceive",
  "enganei": "I deceived",
  "enganou": "deceived",
  "engodo": "trick",
  "entre": "between",
  "entregam": "they deliver",
  "entregar": "to deliver",
  "então": "then",
  "equipa": "team",
  "era": "was",
  "eram": "were",
  "eras": "you were",
  "escola": "school",
  "escudos": "shields",
  "escuto": "I listen",
  "espanha": "spain",
  "espera": "wait",
  "esperto": "smart",
  "espinhas": "thorns",
  "espírito": "spirit",
  "essa": "that",
  "esse": "that",
  "esses": "those",
  "esta": "this",
  "estados": "states",
  "estamos": "we are",
  "estar": "to be",
  "estas": "these",
  "estava": "was",
  "este": "this",
  "estiver": "be",
  "estou": "I am",
  "estranhas": "strange",
  "estranho": "strange",
  "está": "is",
  "estás": "you are",
  "estão": "they are",
  "eu": "I",
  "europa": "europe",
  "euros": "euros",
  "exageraram": "exaggerated",
  "exigiu": "demanded",
  "expandir": "expand",
  "experimenta": "try",
  "faca": "knife",
  "fala": "speaks",
  "falar": "to speak",
  "fartos": "fed up",
  "faz": "does",
  "fazem": "they do",
  "fazemos": "we do",
  "fazer": "to do",
  "fazes": "you do",
  "fechar": "to close",
  "felizes": "happy",
  "ferrugem": "rust",
  "fez": "did",
  "fica": "stays",
  "ficar": "to stay",
  "ficas": "you stay",
  "ficassem": "they stayed",
  "fila": "line",
  "filho": "son",
  "filme": "movie",
  "fiquei": "I stayed",
  "fizemos": "we did",
  "foda": "fuck",
  "fodam": "fuck",
  "fodas": "fuck",
  "foder": "to fuck",
  "fodia": "was fucking",
  "fodidos": "fucked",
  "foi": "was",
  "fome": "hunger",
  "fora": "outside",
  "foram": "they were",
  "forem": "they are",
  "formoso": "handsome",
  "formulário": "form",
  "forte": "strong",
  "fosse": "was",
  "foste": "you were",
  "fotografias": "photographs",
  "fotos": "photos",
  "fotógrafo": "photographer",
  "francesco": "francesco",
  "franja": "fringe",
  "frente": "front",
  "fresca": "fresh",
  "fugir": "to flee",
  "fui": "I was",
  "fumar": "to smoke",
  "funciona": "works",
  "gajas": "girls",
  "gajo": "guy",
  "gajos": "guys",
  "gente": "people",
  "gianluca": "gianluca",
  "gira": "cool",
  "giro": "cool",
  "gomes": "gomes",
  "gosto": "I like",
  "gozar": "to enjoy",
  "grande": "big",
  "guarda": "guard",
  "guardar": "to keep",
  "guito": "money",
  "haxixe": "hashish",
  "história": "story",
  "histórias": "stories",
  "hoje": "today",
  "homem": "man",
  "homens": "men",
  "hora": "hour",
  "horas": "hours",
  "hospital": "hospital",
  "hotel": "hotel",
  "há": "there is",
  "hã": "huh",
  "ia": "was going",
  "idiota": "idiot",
  "ilegal": "illegal",
  "ilha": "island",
  "ilhas": "islands",
  "imoral": "immoral",
  "importa": "matters",
  "importante": "important",
  "impossíveis": "impossible",
  "incluído": "included",
  "iniciados": "initiated",
  "insistes": "you insist",
  "inspetor": "inspector",
  "inspetora": "inspector",
  "interessa": "interests",
  "ir": "to go",
  "isolamento": "isolation",
  "isso": "that",
  "isto": "this",
  "italiano": "italian",
  "italianos": "italians",
  "jantar": "dinner",
  "jeito": "way",
  "jeremias": "jeremias",
  "joelhinho": "little knee",
  "joelho": "knee",
  "jogar": "to play",
  "jogo": "game",
  "jogos": "games",
  "joguei": "I played",
  "judiciária": "judicial",
  "junho": "june",
  "junta": "board",
  "juntas": "boards",
  "justiça": "justice",
  "já": "already",
  "la": "there",
  "lado": "side",
  "lançar": "to launch",
  "larga": "loose",
  "legalizar": "legalize",
  "lei": "law",
  "leme": "helm",
  "leste": "east",
  "levantar": "to lift",
  "levar": "to take",
  "levaram": "they took",
  "levavas": "you took",
  "levou": "took",
  "levá": "take",
  "lhe": "him/her",
  "lhes": "them",
  "liga": "league",
  "linda": "beautiful",
  "lindo": "beautiful",
  "linha": "line",
  "lixar": "to bother",
  "lo": "him",
  "lobo": "wolf",
  "longe": "far",
  "louco": "crazy",
  "lugar": "place",
  "lá": "there",
  "língua": "language",
  "macacos": "monkeys",
  "mafiosos": "mafiosos",
  "maior": "bigger",
  "mais": "more",
  "mal": "bad",
  "maluco": "crazy",
  "manda": "send",
  "mandamos": "we send",
  "maneira": "way",
  "maniche": "maniche",
  "mano": "bro",
  "mantém": "keeps",
  "mar": "sea",
  "maravilha": "wonder",
  "marcada": "marked",
  "mas": "but",
  "massimo": "massimo",
  "mataram": "they killed",
  "matrix": "matrix",
  "matámos": "we killed",
  "mayday": "mayday",
  "me": "me",
  "mecânico": "mechanic",
  "medo": "fear",
  "meio": "half",
  "melhor": "better",
  "melhorar": "to improve",
  "melhores": "best",
  "melo": "melo",
  "menezes": "menezes",
  "menisco": "meniscus",
  "menos": "less",
  "mercado": "market",
  "merda": "shit",
  "merdas": "shits",
  "merecer": "to deserve",
  "meses": "months",
  "mesmas": "same",
  "mesmo": "same",
  "metem": "they put",
  "meu": "my",
  "mexe": "move",
  "miguel": "miguel",
  "mijar": "to piss",
  "mil": "thousand",
  "milagres": "miracles",
  "milhares": "thousands",
  "milhões": "millions",
  "mim": "me",
  "minha": "my",
  "minhas": "my",
  "miss": "miss",
  "missa": "mass",
  "mito": "myth",
  "miúdo": "kid",
  "moca": "high",
  "moda": "fashion",
  "molhado": "wet",
  "molho": "sauce",
  "momento": "moment",
  "moradores": "residents",
  "morrer": "to die",
  "morreremos": "we will die",
  "morreu": "died",
  "morto": "dead",
  "mostra": "show",
  "mostravam": "they showed",
  "movida": "movement",
  "mudar": "to change",
  "muito": "much",
  "mulher": "woman",
  "mundo": "world",
  "murchas": "withered",
  "má": "bad",
  "mãe": "mother",
  "mãos": "hands",
  "música": "music",
  "na": "in the",
  "nada": "nothing",
  "namorado": "boyfriend",
  "nariz": "nose",
  "negócio": "business",
  "nele": "in him",
  "nem": "not even",
  "nenhuma": "none",
  "nessa": "in that",
  "nesta": "in this",
  "neste": "in this",
  "neve": "snow",
  "ninguém": "nobody",
  "no": "in the",
  "noites": "nights",
  "norte": "north",
  "nos": "us",
  "nossa": "our",
  "nosso": "our",
  "notam": "they notice",
  "notícias": "news",
  "nova": "new",
  "nove": "nine",
  "noventa": "ninety",
  "novidades": "news",
  "novo": "new",
  "num": "in a",
  "numa": "in a",
  "nunca": "never",
  "nuno": "nuno",
  "não": "no",
  "nós": "we",
  "números": "numbers",
  "o": "the",
  "obrigada": "thank you",
  "obrigado": "thank you",
  "oeste": "west",
  "oh": "oh",
  "oitocentos": "eight hundred",
  "olha": "look",
  "olhe": "look",
  "olhem": "look",
  "olhos": "eyes",
  "olá": "hello",
  "onda": "wave",
  "onde": "where",
  "ontem": "yesterday",
  "operado": "operated",
  "operação": "operation",
  "oportunidade": "opportunity",
  "os": "the",
  "ou": "or",
  "outras": "others",
  "outros": "others",
  "ouve": "hears",
  "ouviste": "you heard",
  "padre": "priest",
  "pagar": "to pay",
  "pai": "father",
  "palmo": "span",
  "para": "for",
  "parar": "to stop",
  "pare": "stop",
  "parece": "seems",
  "pareciam": "they seemed",
  "parte": "part",
  "partes": "parts",
  "partiu": "left",
  "passa": "passes",
  "passaram": "passed",
  "passas": "you pass",
  "passo": "step",
  "passou": "passed",
  "patinagem": "skating",
  "patrão": "boss",
  "paula": "paula",
  "pedir": "to ask",
  "pedires": "you ask",
  "pega": "catch",
  "peida": "fart",
  "peixe": "fish",
  "pela": "by the",
  "pelo": "by the",
  "pensei": "I thought",
  "penses": "you think",
  "pequena": "small",
  "pequeno": "small",
  "percebe": "understands",
  "perceber": "to understand",
  "percebes": "you understand",
  "percebeu": "understood",
  "percebia": "understood",
  "perdemos": "we lose",
  "perder": "to lose",
  "perdidas": "lost",
  "perdido": "lost",
  "perigosa": "dangerous",
  "permitiram": "they allowed",
  "pesca": "fishing",
  "pesseguinha": "little peach",
  "pessoa": "person",
  "pessoas": "people",
  "peça": "piece",
  "pila": "cock",
  "pintxa": "pintxa",
  "pior": "worse",
  "planeta": "planet",
  "poborsky": "poborsky",
  "pobres": "poor",
  "pobreza": "poverty",
  "pode": "can",
  "podemos": "we can",
  "poder": "to be able",
  "poderá": "can",
  "podes": "you can",
  "podia": "could",
  "podias": "you could",
  "pois": "well",
  "policial": "police",
  "polícia": "police",
  "ponho": "I put",
  "pontos": "points",
  "por": "by",
  "porcaria": "trash",
  "pores": "you put",
  "porque": "because",
  "porquê": "why",
  "porra": "fuck",
  "porto": "porto",
  "portugal": "portugal",
  "portugueses": "portuguese",
  "português": "portuguese",
  "possas": "you can",
  "posso": "I can",
  "pouco": "little",
  "praia": "beach",
  "prazer": "pleasure",
  "precedentes": "precedents",
  "precisa": "needs",
  "precisavas": "you needed",
  "preciso": "I need",
  "preencher": "to fill",
  "preferias": "you preferred",
  "preocupar": "to worry",
  "presas": "prisoners",
  "presente": "present",
  "prestes": "ready",
  "preço": "price",
  "primeira": "first",
  "primeiro": "first",
  "prisão": "prison",
  "problema": "problem",
  "procissão": "procession",
  "procurá": "look for",
  "profissional": "professional",
  "pronto": "ready",
  "prova": "proof",
  "prémio": "prize",
  "próxima": "next",
  "pudesse": "could",
  "punheta": "wank",
  "puro": "pure",
  "puseram": "they put",
  "puta": "whore",
  "putinha": "little whore",
  "puxes": "you pull",
  "pá": "dude",
  "põe": "put",
  "pões": "you put",
  "quando": "when",
  "quanto": "how much",
  "quantos": "how many",
  "que": "that",
  "quem": "who",
  "quer": "want",
  "querem": "they want",
  "queremos": "we want",
  "queres": "you want",
  "queria": "wanted",
  "quero": "I want",
  "quieto": "quiet",
  "quilo": "kilo",
  "quilos": "kilos",
  "quilómetros": "kilometers",
  "quiseres": "you want",
  "quites": "even",
  "quê": "what",
  "rabo": "ass",
  "rafael": "rafael",
  "rapaz": "boy",
  "rapazim": "little boy",
  "ratos": "rats",
  "rebento": "sprout",
  "recorde": "record",
  "recuperamos": "we recover",
  "recuperar": "to recover",
  "redes": "networks",
  "regressamos": "we return",
  "rei": "king",
  "remate": "shot",
  "repita": "repeat",
  "resolve": "solve",
  "resposta": "answer",
  "resto": "rest",
  "resultar": "to result",
  "ricos": "rich",
  "rivais": "rivals",
  "rua": "street",
  "sabermos": "we know",
  "saberá": "will know",
  "sabes": "you know",
  "sabonete": "soap",
  "sagradas": "sacred",
  "sai": "leaves",
  "saio": "I leave",
  "sair": "to leave",
  "sangrar": "to bleed",
  "sanita": "toilet",
  "santo": "saint",
  "se": "if",
  "secundário": "secondary",
  "seguir": "to follow",
  "segundo": "second",
  "sei": "I know",
  "seis": "six",
  "sejam": "be",
  "sem": "without",
  "semanas": "weeks",
  "sempre": "always",
  "senhor": "mr",
  "senhora": "mrs",
  "ser": "to be",
  "serem": "to be",
  "serve": "serves",
  "sete": "seven",
  "sexta": "friday",
  "sextas": "fridays",
  "sim": "yes",
  "sina": "destiny",
  "sinal": "sign",
  "sistema": "system",
  "situação": "situation",
  "sky": "sky",
  "sobre": "about",
  "sobretudo": "especially",
  "sono": "sleep",
  "sorte": "luck",
  "sossegas": "calm down",
  "sou": "I am",
  "sozinha": "alone",
  "sr": "mr",
  "sua": "his/her",
  "subsídio": "subsidy",
  "são": "are",
  "século": "century",
  "séculos": "centuries",
  "sílvia": "sílvia",
  "sítio": "place",
  "só": "only",
  "súper": "super",
  "taco": "taco",
  "talvez": "maybe",
  "também": "also",
  "tanto": "so much",
  "tantos": "so many",
  "tarda": "late",
  "tarde": "late",
  "te": "you",
  "televisão": "television",
  "tem": "has",
  "temos": "we have",
  "tempestade": "storm",
  "tempestades": "storms",
  "tempo": "time",
  "tenho": "I have",
  "tens": "you have",
  "tento": "try",
  "ter": "to have",
  "terceira": "third",
  "terra": "land",
  "teu": "your",
  "ti": "you",
  "tinha": "had",
  "tiqui": "tiqui",
  "tirar": "to take",
  "tirares": "you take",
  "tiras": "you take",
  "tirinho": "little shot",
  "tiro": "shot",
  "tive": "I had",
  "tivesse": "had",
  "tivesses": "you had",
  "toda": "all",
  "todas": "all",
  "todo": "all",
  "toma": "take",
  "tomar": "to take",
  "tomaram": "they took",
  "tomates": "tomatoes",
  "tomámos": "we took",
  "toques": "touches",
  "transmissão": "transmission",
  "trata": "treats",
  "tratado": "treaty",
  "tratar": "to treat",
  "trazer": "to bring",
  "trazes": "you bring",
  "tretas": "nonsense",
  "trezentos": "three hundred",
  "trouxe": "brought",
  "três": "three",
  "tu": "you",
  "tua": "your",
  "tubarões": "sharks",
  "tudo": "everything",
  "turista": "tourist",
  "turma": "class",
  "tão": "so",
  "têm": "they have",
  "uh": "uh",
  "ui": "oops",
  "um": "a",
  "uma": "a",
  "umas": "some",
  "unidos": "united",
  "uns": "some",
  "urgências": "emergencies",
  "vai": "goes",
  "vais": "you go",
  "valor": "value",
  "vamo": "let's go",
  "vamos": "let's go",
  "veio": "came",
  "veleiro": "sailboat",
  "vem": "comes",
  "vendiam": "they sold",
  "veneno": "poison",
  "venho": "I come",
  "ver": "to see",
  "verdade": "truth",
  "vergar": "to bend",
  "vez": "time",
  "vezes": "times",
  "vi": "I saw",
  "viagem": "trip",
  "viajas": "you travel",
  "vida": "life",
  "viemos": "we came",
  "vindo": "coming",
  "vinho": "wine",
  "vinte": "twenty",
  "vir": "to come",
  "vista": "view",
  "viste": "you saw",
  "visto": "seen",
  "viver": "to live",
  "viveram": "they lived",
  "vocês": "you",
  "volante": "steering wheel",
  "volta": "turn",
  "vontade": "will",
  "voo": "flight",
  "vou": "I go",
  "vulcões": "volcanoes",
  "vá": "go",
  "vários": "various",
  "vão": "they go",
  "vê": "see",
  "vêm": "they come",
  "xv": "xv",
  "zarpamos": "we set sail",
  "zero": "zero",
  "ª": "ª",
  "à": "to the",
  "às": "to the",
  "água": "water",
  "é": "is",
  "ó": "oh",
  "última": "last"
};